title: Fair Transfomer GAN
description: A genertive model architecture for mitigating algorithmic bias.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple

logo: "logo2.png"

favicon_ico: "favicon.ico"
